// Generated by CoffeeScript 1.10.0
var Game;

Game = function(canvas) {
  this.canvas = canvas;
};

Game.prototype.ID = 0;

Game.prototype.player = void 0;

Game.prototype.scene = void 0;

Game.prototype.objects = [];

Game.prototype.engine = void 0;

Game.prototype.startGame = function(objects) {
  var retObject;
  Game.prototype.engine = new BABYLON.Engine(this.canvas, true);
  retObject = RSC.Game(this.canvas, Game.prototype.engine, objects, Game.prototype.ID);
  Game.prototype.player = retObject.me;
  Game.prototype.scene = retObject.scene;
  return Game.prototype.engine.runRenderLoop(this.gameLoop);
};

Game.prototype.handleNetwork = function(socket) {
  var toStart;
  console.log(socket);
  toStart = this;
  socket.on('roomJoin', function(objects, ID) {
    document.getElementById('textArea').innerHTML = "Joined a game!";
    Game.prototype.ID = ID;
    console.log("Received this player's id of " + ID);
    return toStart.startGame(objects);
  });
};

Game.prototype.gameLoop = function() {
  Game.prototype.scene.render();
};
